Repository Groupify-SCE/Groupify-Backend, pull requests merged in 2025-05, with the labels that each got.

#44 Add delete participant route and handler
  src/routes/projects/participants/index.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#45 Add updateAllParticipants endpoint and manager logic
  src/routes/projects/participants/index.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#46 Feature/preference form
  src/routes/projects/index.ts
  src/routes/projects/types.ts
  src/utils/services/projects.manager.ts
Labels: new feature

#52 Feature/run algorithm
  src/app.ts
  src/routes/algorithm/index.ts
  src/utils/algorithm/crossover.ts
  src/utils/algorithm/fitness.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/mutate.ts
  src/utils/algorithm/selection.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/algorithm/updatePopulation.ts
  src/utils/services/database.manager.ts
  src/utils/services/projects.manager.ts
Labels: new feature

#53 Feature/view groups
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/utils/algorithm/mutate.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/services/database.manager.ts
  src/utils/services/projects.manager.ts
Labels: new feature

#54 Finished sprint 6
  src/app.ts
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/utils/algorithm/crossover.ts
  src/utils/algorithm/fitness.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/mutate.ts
  src/utils/algorithm/selection.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/algorithm/updatePopulation.ts
  src/utils/services/database.manager.ts
  src/utils/services/projects.manager.ts
Labels: DevOps

#56 Feature/add unit tests
  tests/routes/algorithm.test.ts
  tests/routes/auth.test.ts
  tests/routes/projects.test.ts
  tests/routes/user.test.ts
Labels: enhancement

#57 fixed algorithm index
  .dockerignore
  Dockerfile
  docker-compose.yml
  tests/routes/algorithm.test.ts
  tests/routes/auth.test.ts
  tests/routes/projects.test.ts
  tests/routes/user.test.ts
Labels: DevOps

#58 Update index.ts
  src/routes/algorithm/index.ts
Labels: DevOps

#59 fixed github issue
  src/app.ts
  src/routes/algorithm/types.ts
  src/utils/algorithm/crossover.ts
  src/utils/algorithm/fitness.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/mutate.ts
  src/utils/algorithm/selection.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/algorithm/updatePopulation.ts
  src/utils/services/database.manager.ts
  src/utils/services/projects.manager.ts
Labels: DevOps

#60 Fixed issues with v0.6.0
  .dockerignore
  Dockerfile
  docker-compose.yml
  src/app.ts
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/utils/algorithm/crossover.ts
  src/utils/algorithm/fitness.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/mutate.ts
  src/utils/algorithm/selection.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/algorithm/updatePopulation.ts
  src/utils/services/database.manager.ts
  src/utils/services/projects.manager.ts
  tests/routes/algorithm.test.ts
  tests/routes/auth.test.ts
  tests/routes/projects.test.ts
  tests/routes/user.test.ts
Labels: DevOps
