Repository Groupify-SCE/Groupify-Backend, pull requests merged in 2025-02, with the labels that each got.

#2 set up environment
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  src/app.ts
  tsconfig.json
Labels: DevOps

#3 Update CICD to add deployment
  .github/workflows/cicd.yml
Labels: DevOps

#4 Created basic express.js app with typescript
  .eslintignore
  .eslintrc.js
  .github/workflows/cicd.yml
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  src/app.ts
  tsconfig.json
Labels: new feature

#5 Added jest tests
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  tests/app.test.ts
  tsconfig.json
Labels: new feature

#6 added tests
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  tests/app.test.ts
  tsconfig.json
Labels: new feature

#7 Created express app with typescript
  .eslintignore
  .eslintrc.js
  .github/workflows/cicd.yml
  .gitignore
  .prettierrc
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  tests/app.test.ts
  tsconfig.json
Labels: new feature

#9 Setup basic cors for developing
  package-lock.json
  package.json
  src/app.ts
Labels: bug

#10 Feature/add login route
  src/routes/auth/index.ts
  src/routes/auth/types.ts
  src/utils/services/auth.manager.ts
Labels: enhancement

#11 Feature/auth status
  package-lock.json
  package.json
  src/app.ts
  src/routes/auth/index.ts
  src/routes/auth/types.ts
  src/utils/middleware/authToken.middleware.ts
  src/utils/middleware/expressTypes.ts
  src/utils/services/auth.manager.ts
Labels: enhancement

#12 Feature/add reset password
  package-lock.json
  package.json
  src/app.ts
  src/routes/auth/index.ts
  src/routes/auth/types.ts
  src/utils/emails/resetPassword.ejs
  src/utils/services/auth.manager.ts
  src/utils/services/email.service.ts
Labels: enhancement
