Repository Groupify-SCE/Groupify-Backend, pull requests merged in 2025-03, with the labels that each got.

#13 Feature/add algorithm route
  package-lock.json
  package.json
  src/app.ts
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/services/auth.manager.ts
  src/utils/services/database.manager.ts
Labels: enhancement

#14 Feature/profile details
  src/app.ts
  src/routes/user/index.ts
  src/routes/user/types.ts
  src/utils/services/auth.manager.ts
Labels: new feature

#15 Sprint 3
  package-lock.json
  package.json
  src/app.ts
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/routes/auth/index.ts
  src/routes/auth/types.ts
  src/routes/user/index.ts
  src/routes/user/types.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/emails/resetPassword.ejs
  src/utils/middleware/authToken.middleware.ts
  src/utils/middleware/expressTypes.ts
  src/utils/middleware/validation.middleware.ts
  src/utils/services/auth.manager.ts
  src/utils/services/database.manager.ts
  src/utils/services/email.service.ts
  src/utils/services/jwt.service.ts
Labels: DevOps

#16 Stage
  .eslintignore
  .eslintrc.js
  .github/workflows/cicd.yml
  .gitignore
  .prettierrc
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/routes/auth/index.ts
  src/routes/auth/types.ts
  src/routes/user/index.ts
  src/routes/user/types.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/emails/resetPassword.ejs
  src/utils/middleware/authToken.middleware.ts
  src/utils/middleware/expressTypes.ts
  src/utils/middleware/validation.middleware.ts
  src/utils/services/auth.manager.ts
  src/utils/services/database.manager.ts
  src/utils/services/email.service.ts
  src/utils/services/jwt.service.ts
  tests/app.test.ts
  tsconfig.json
Labels: bug

#17 Hotfix
  .github/workflows/cicd.yml
Labels: bug

#19 Hotfix
  .github/workflows/cicd.yml
Labels: bug

#20 V0.3.0
  .github/workflows/cicd.yml
  package-lock.json
  package.json
  src/app.ts
  src/routes/algorithm/index.ts
  src/routes/algorithm/types.ts
  src/routes/auth/index.ts
  src/routes/auth/types.ts
  src/routes/user/index.ts
  src/routes/user/types.ts
  src/utils/algorithm/geneticAlgorithm.ts
  src/utils/algorithm/initializeGroupingAlgorithm.ts
  src/utils/algorithm/student.object.ts
  src/utils/algorithm/types.ts
  src/utils/emails/resetPassword.ejs
  src/utils/middleware/authToken.middleware.ts
  src/utils/middleware/expressTypes.ts
  src/utils/middleware/validation.middleware.ts
  src/utils/services/auth.manager.ts
  src/utils/services/database.manager.ts
  src/utils/services/email.service.ts
  src/utils/services/jwt.service.ts
Labels: DevOps

#21 fix: Fixed cookies in production
  src/routes/auth/index.ts
Labels: bug

#22 Hotfix
  src/routes/auth/index.ts
Labels: bug

#23 Sprint 3: Fixed cookies bug in production
  src/routes/auth/index.ts
Labels: DevOps

#25 Feature/create project
  src/app.ts
  src/routes/projects/index.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#26 get all projects
  src/routes/projects/index.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#30 fixed input
  src/routes/projects/types.ts
Labels: enhancement

#31 Finished sprint 4
  src/app.ts
  src/routes/projects/index.ts
  src/routes/projects/types.ts
  src/utils/services/projects.manager.ts
Labels: DevOps

#33 Feature/add criteria
  src/routes/projects/criteria/index.ts
  src/routes/projects/criteria/types.ts
  src/routes/projects/index.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#34 Feature/get project criteria
  src/routes/projects/criteria/index.ts
  src/routes/projects/criteria/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#35 Feature/update criterion
  src/routes/projects/criteria/index.ts
  src/routes/projects/criteria/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#36 Feature/delete criteria
  src/routes/projects/criteria/index.ts
  src/routes/projects/criteria/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#37 fixed unnecessary fields
  src/routes/projects/criteria/index.ts
  src/routes/projects/criteria/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#32 Finished Version 0.4.0
  src/app.ts
  src/routes/projects/index.ts
  src/routes/projects/types.ts
  src/utils/services/projects.manager.ts
Labels: DevOps

#38 Feature/add participent
  src/routes/projects/criteria/index.ts
  src/routes/projects/index.ts
  src/routes/projects/participants/index.ts
  src/routes/projects/participants/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#39 Update types.ts
  src/routes/projects/participants/types.ts
Labels: enhancement

#40 Feature/get all
  src/routes/projects/participants/index.ts
  src/routes/projects/participants/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#41 Feature/add criteria button
  src/routes/projects/participants/index.ts
  src/routes/projects/participants/types.ts
  src/utils/services/projects.manager.ts
Labels: enhancement

#42 Feature/update participant criteria connection
  src/utils/services/projects.manager.ts
Labels: enhancement
